const ActionTypes = {
  ADD_TODO: 'ADD_TODO',
  ADD_SUCCEEDED: 'ADD_SUCCEEDED',
  ADD_FAILED: 'ADD_FAILED',

  REMOVE_TODO: 'REMOVE_TODO',
  REMOVE_SUCCEEDED: 'REMOVE_SUCCEEDED',
  REMOVE_FAILED: 'REMOVE_FAILED',

  TOGGLE_TODO: 'TOGGLE_TODO',
  TOGGLE_SUCCEEDED: 'TOGGLE_SUCCEEDED',
  TOGGLE_FAILED: 'TOGGLE_FAILED',

  FETCH_TODOS: 'FETCH_TODOS',
  FETCH_SUCCEEDED: 'FETCH_SUCCEEDED',
  FETCH_FAILED: 'FETCH_FAILED',
}

export default ActionTypes;
